# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Migrador.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaPrincipal(object):
    def setupUi(self, TelaPrincipal):
        TelaPrincipal.setObjectName("TelaPrincipal")
        TelaPrincipal.resize(637, 346)
        self.textEdit = QtWidgets.QTextEdit(TelaPrincipal)
        self.textEdit.setGeometry(QtCore.QRect(40, 40, 131, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(TelaPrincipal)
        self.pushButton.setGeometry(QtCore.QRect(190, 40, 91, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(TelaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(TelaPrincipal)

    def retranslateUi(self, TelaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        TelaPrincipal.setWindowTitle(_translate("TelaPrincipal", "Dialog"))
        self.pushButton.setText(_translate("TelaPrincipal", "Migrar"))
